/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp6;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;

class AppTest {
    private Club club;
    private EntityManagerImpl em;

    @BeforeEach
    public void setUp() throws Exception {
        club = new Club();
        club.setFabricant("Adidos");
        club.setPoids(10.3);
        
        em = new EntityManagerImpl();
        em.persist(club);
    }

    @Test
    public void testPersistence() {
    assertNotNull(club.getId(), "Club should have an ID after persist");
}

    @Test
    public void testFind() throws SQLException {
    Club trouve = em.<Club> find(Club.class, club.getId());
    assertEquals(club.getFabricant(), trouve.getFabricant());
}

    @Test
    public void shouldReturnNullWhenFindingNonExistentClub() throws SQLException {
    Club trouve = em.<Club> find(Club.class, 9999);
    assertNull(trouve, "Should return null when finding a club with non-existent id");
    }
}